# Generated by Django 2.0.6 on 2018-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_owner', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('like', models.CharField(max_length=50)),
                ('follow', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Профили',
                'verbose_name': 'Профиль',
            },
        ),
    ]
