# Generated by Django 2.0.6 on 2018-06-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
        ('instagram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.Authentication'),
        ),
    ]
